= RivetzStub

RivetzJ Source Project

See https://epistery.com/do/view/Main/RivetzStub[RivetzStub on the wiki] for deployment instructions.

== Modules

We're in the middle of some refactoring. Not all these modules are complete and the API is subject to change. There are currently 4 modules:

* `rivetz-bridge` - Rivetz Android library (`.aar` extension)
* `rivetz-lib` - Rivetz main Java library (`.jar` extension)
* `rivetz-test` - contains the `RivetSimulator` and other components for testing
* `rivetz-server` - demonstration Rivetz server built using http://projects.spring.io/spring-boot/[Spring Boot]

== Building with Gradle

=== Full Build

To do a full build with Gradle

    ./gradlew clean build

This should build each of the modules producing outputs in their respective `build` directories.

==== Viewing Unit Test results

For now only `rivetz-lib` and `rivetz-test` have any unit tests. To view the results after a build, open the following files:

* `rivetz-lib/build/reports/tests/index.html`
* `rivetz-test/build/reports/tests/index.html`

==== Publishing Artifacts to your local Maven Repo

If you are making changes to RivetzJ and want to use and/or test them in another project, you should set a snapshot `version` property the root `build.gradle`, as shown:

[source,groovy]
-------
    allprojects {
        version =  '0.0.7-SNAPSHOT' // <1>
        group = 'com.rivetz'
        // <2>
    }
-------
<1> Add the `-SNAPSHOT` suffix to the `version` property.
<2> Other lines of configuration go here and were omitted for this example.

Update the declared dependencies in your dependent projects to use the same `-SNAPSHOT` version and make sure they include the `mavenLocal()` repository in the `repositories` config block, as shown:

[source,groovy]
-------
    repositories {
        mavenLocal()    // <1>
        // <2>
    }
-------
<1> Search the local Maven repository for artifacts, including snapshots.
<2> Other lines of configuration go here and were omitted for this example.

[source,groovy]
-------
dependencies {
    compile 'com.rivetz:rivetz-bridge:0.0.7-SNAPSHOT@aar'    // Rivetz Android Library
    compile 'com.rivetz:rivetz-lib:0.0.7-SNAPSHOT'           // Rivetz Core Java Library
        // <1>
}
-------
<1> Other dependency lines go here and were omitted for this example.

To publish your snapshot release of RivetzJ to your local maven repository (Typically in `~/.m2/` on UNIX systems) use the following Gradle command:

    ./gradlew install

If the version is `0.0.7-SNAPSHOT` you should then see the following files published to your local Maven repository:

-------
~/.m2/repository/com/rivetz/rivetz-bridge/0.0.7-SNAPSHOT/rivetz-bridge-0.0.7-SNAPSHOT.aar
~/.m2/repository/com/rivetz/rivetz-lib/0.0.7-SNAPSHOT/rivetz-lib-0.0.7-SNAPSHOT.jar
~/.m2/repository/com/rivetz/rivetz-test/0.0.7-SNAPSHOT/rivetz-test-0.0.7-SNAPSHOT.jar
-------


=== Running the Server from Gradle

To run the Rivetz Demo Server using Spring Boot:

    ./gradlew :rivetz-server:bootRun

At this point the server is only a "hello world"-style server. To test it, open: http://localhost:8080/hello

=== Building the Server

To build the server into a Spring Boot executable JAR:

    ./gradlew :rivetz-server:assemble

To run the server use:

    java -jar rivetz-server/build/libs/rivetz-server-0.1.jar

=== Building Documentation

Although most documentation is on the website and wiki, there is some documentation directly in the source repo. 

NOTE: This part of the build requires that the http://www.graphviz.org/Download.php[GraphViz] command-line tool be installed.

To build it:

    ./gradlew asciidoctor

A small amount of UML documentation will be built into the file `./build/adoc/rivet.html`

=== Release to BinTray

    ./gradlew bintrayUpload








